### GET
GET http://localhost:4567/
Accept: application/json



### POST
POST http://localhost:4567/administrators/add
Content-Type: application/json

{
  "firstName": "Ahmed",
  "lastName": "Charif",
  "phoneNumber": "0666234971",
  "email": "ahmed.charif@gmail.com",
  "password": "Ahmed@#2021"
}
